services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    network_mode: service:selenium
    command: sleep infinity
    volumes:
      - ..:/workspaces/keiba-mcp:cached

  selenium:
    image: selenium/standalone-chromium
